export enum EStatusHttp {
  HTTP_TOKEN_INVALID = 99,
  HTTP_FORBIDDEN = 403,
  HTTP_UNAUTHORIZED = 401,
  HTTP_OK = 200,
  HTTP_CREATED = 201,
  HTTP_TOO_MANY_REQUESTS = 429,
  HTTP_NOT_FOUND = 404,
  HTTP_BAD_REQUEST = 400,
  HTTP_INTERNAL_SERVER_ERROR = 500,
  HTTP_CONFLICT = 409,
  HTTP_UNPROCESSABLE_ENTITY = 422,
  HTTP_SERVICE_UNAVAILABLE = 503,
}

export enum EStatusCodeData {
  FAILS = 'fails',
  ERROR = 'error',
  SUCCESS = 'success',
}
